Repository honojs/hono, pull requests merged in 2024-09, with the labels that each got.

#3314 feat(secureHeader): add Permissions-Policy header to secure headers middleware
  src/middleware/secure-headers/index.test.ts
  src/middleware/secure-headers/permissions-policy.ts
  src/middleware/secure-headers/secure-headers.ts
Labels: approved, v4.6

#3332 feat(cloudflare-pages): enable `c.env.eventContext` in `handleMiddleware`
  src/adapter/cloudflare-pages/handler.test.ts
  src/adapter/cloudflare-pages/handler.ts
Labels: approved, v4.6

#3337 feat(websocket): Add generics type to `WSContext`
  src/adapter/bun/websocket.ts
  src/adapter/cloudflare-workers/websocket.ts
  src/adapter/deno/websocket.ts
  src/helper/websocket/index.ts
Labels: approved, v4.6

#3355 feat(jsx-renderer): set `Content-Encoding` when `stream` is `true`
  src/middleware/jsx-renderer/index.test.tsx
  src/middleware/jsx-renderer/index.ts
Labels: approved, v4.6

#3373 feat(contextStorage): added Context Storage Middleware
  jsr.json
  package.json
  src/middleware/context-storage/index.test.ts
  src/middleware/context-storage/index.ts
Labels: approved, v4.6

#3366 feat(serveStatic): add `precompressed` option
  src/middleware/serve-static/index.test.ts
  src/middleware/serve-static/index.ts
Labels: approved, v4.6

#3344 feat(helper/streaming): Support Promise<string> or (async) JSX.Element in streamSSE
  src/context.ts
  src/helper/streaming/sse.test.tsx
  src/helper/streaming/sse.ts
  src/utils/html.ts
Labels: approved, v4.6

#3318 feat(context): make fetch Response headers mutable
  runtime_tests/node/index.test.ts
  src/context.test.ts
  src/context.ts
Labels: approved, v4.6

#3396 feat(serve-static): add `onFound` option
  src/middleware/serve-static/index.test.ts
  src/middleware/serve-static/index.ts
Labels: v4.6

#3371 feat(basic-auth): added custom response message option
  src/middleware/basic-auth/index.test.ts
  src/middleware/basic-auth/index.ts
Labels: approved, v4.6

#3372 feat(bearer-auth): added custom response message options
  src/middleware/bearer-auth/index.test.ts
  src/middleware/bearer-auth/index.ts
Labels: approved, v4.6

#3394 Next
  jsr.json
  package.json
  runtime_tests/node/index.test.ts
  src/adapter/bun/websocket.ts
  src/adapter/cloudflare-pages/handler.test.ts
  src/adapter/cloudflare-pages/handler.ts
  src/adapter/cloudflare-workers/websocket.ts
  src/adapter/deno/websocket.ts
  src/context.test.ts
  src/context.ts
  src/helper/streaming/sse.test.tsx
  src/helper/streaming/sse.ts
  src/helper/websocket/index.ts
  src/middleware/basic-auth/index.test.ts
  src/middleware/basic-auth/index.ts
  src/middleware/bearer-auth/index.test.ts
  src/middleware/bearer-auth/index.ts
  src/middleware/context-storage/index.test.ts
  src/middleware/context-storage/index.ts
  src/middleware/jsx-renderer/index.test.tsx
  src/middleware/jsx-renderer/index.ts
  src/middleware/secure-headers/index.test.ts
  src/middleware/secure-headers/permissions-policy.ts
  src/middleware/secure-headers/secure-headers.ts
  src/middleware/serve-static/index.test.ts
  src/middleware/serve-static/index.ts
  src/utils/html.ts
Labels: v4.6

#3413 feat(secureHeader): add CSP Report-Only mode support
  src/middleware/secure-headers/index.test.ts
  src/middleware/secure-headers/secure-headers.ts
Labels: approved

#3425 feat(request): Make request.ts available throught JSR for frameworks that need to instantiate HonoRequest
  jsr.json
Labels: approved

#3432 feat(jsx/precompile): Normalization and stringification of attribute values as `renderToString`
  runtime-tests/deno-jsx/jsx.test.tsx
  src/jsx/base.ts
  src/jsx/jsx-runtime.ts
Labels: approved

#3420 feat(serve-static): support absolute root
  runtime-tests/bun/index.test.tsx
  runtime-tests/bun/static-absolute-root/plain.txt
  runtime-tests/deno/.vscode/settings.json
  runtime-tests/deno/deno.json
  runtime-tests/deno/deno.lock
  runtime-tests/deno/middleware.test.tsx
  runtime-tests/deno/static-absolute-root/plain.txt
  src/adapter/bun/serve-static.ts
  src/adapter/deno/serve-static.ts
  src/middleware/serve-static/index.test.ts
  src/middleware/serve-static/index.ts
  src/utils/filepath.ts
Labels: approved
